# Generated by Django 4.0.4 on 2022-07-21 06:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='summary',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
