# Generated by Django 4.0.4 on 2022-07-21 06:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngos', '0002_school_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='desc',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
