# Generated by Django 4.0.4 on 2022-07-21 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngos', '0003_alter_school_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='desc',
            new_name='description',
        ),
    ]
