# Generated by Django 4.0.4 on 2022-07-21 07:32

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ngos', '0004_rename_desc_school_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='school',
            name='summary',
            field=ckeditor.fields.RichTextField(blank=True, default=''),
        ),
    ]
