# Generated by Django 4.0.4 on 2022-07-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngos', '0005_school_created_at_alter_school_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
